name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        run: npx lerna bootstrap --ci

  tooling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        run: npx lerna bootstrap --ci

      - name: Formating code
        run: npm run format:check

      - name: Testing projects
        run: npm run test

  build-docker-images:
    runs-on: ubuntu-latest
    needs: ["install-dependencies", "tooling"]
    steps:
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{secrets.DOCKER_REGISTRY_URL }}
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_PASSWORD }}
