name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        uses: "MrBoolean/action-lerna@master"
        with:
          args: "bootstrap"

      - name: Formating code
        run: npm run format:check

      - name: Testing projects
        run: npm run test

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the tagged Docker image
        run: docker build -f ./packages/api-catalog/Dockerfile -t sincronize/federated-graphql-cicd-api-catalog:dev .

      - name: Push image
        run: |
          docker push sincronize/federated-graphql-cicd-api-catalog:dev
