name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies-build-docker-image:
    if: "!contains(github.event.head_commit.message, 'skip ci')" # public; ignore commits with `[skip ci]`

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - name: Pulls all tags (needed for lerna to correctly version)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      # - name: Lerna bootstrap
      #   uses: "MrBoolean/action-lerna@master"
      #   with:
      #     args: "bootstrap"

      - run: git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
      - run: git config --global user.name ${{ secrets.GIT_USER_NAME }}

      # SET GIT CREDENTIALS
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Formating code
        run: npm run ci:format:check

      - name: Linter code
        run: npm run ci:lint

      - name: Testing projects
        run: npm run ci:test

      # Print what changed
      - run: ./node_modules/.bin/lerna changed

      - name: Create a new version
        run: yarn new-version

      - run: git tag

      - name: Get last changed tag
        run: |
          echo "::set-env name=LATEST_TAG::$(git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p)"

      - run: echo "$LATEST_TAG"

      - name: Login to DockerHub
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: yarn ci:deploy

      - run: yarn ci:deploy:tag-version
