name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        uses: "MrBoolean/action-lerna@master"
        with:
          args: "bootstrap"

      # - name: Formating code
      #   run: npm run format:check

      # - name: Linter code
      #   run: npm run lint

      # - name: Testing projects
      #   run: npm run test

      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new version
        run: yarn new-version

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: git tag
      - name: Get last changed tag
        run: export TAG=`git describe --abbrev=0 --tags $(git rev-list --tags --max-count=2) | sed -n 2p`

      - run: echo $TAG
      - run: yarn ci:deploy:dev
