name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        run: npx lerna bootstrap --ci

      - uses: actions/checkout@v2

      - name: Formating code
        run: npm run format:check

      - name: Testing projects
        run: npm run test

  build-docker-images:
    runs-on: ubuntu-latest
    needs: ["install-dependencies"]
    steps:
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build image api-catalog
        run: npm run docker:build:api-catalog:dev
