name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna to correctly version)
          # see https://stackoverflow.com/a/60184319/9285308 & https://github.com/actions/checkout
          fetch-depth: "0"

      - name: Pulls all tags (needed for lerna to correctly version)
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* # see https://stackoverflow.com/a/60184319/9285308

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        uses: "MrBoolean/action-lerna@master"
        with:
          args: "bootstrap"

      # - name: Formating code
      #   run: npm run format:check

      # - name: Linter code
      #   run: npm run lint

      # - name: Testing projects
      #   run: npm run test

      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a new version
        run: yarn new-version

      - name: Login to docker hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - run: git tag
      - name: Get last changed tag
        run: |
          echo "::set-env name=LATEST_TAG::$(git describe --tags --abbrev=0)"
          echo $TAG

      - run: yarn ci:deploy:dev
