name: CI

on:
  push:
    branches: [develop]

jobs:
  install-dependencies-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Installing dependencies
        run: npm install

      - name: Lerna bootstrap
        uses: "MrBoolean/action-lerna@master"
        with:
          args: "bootstrap"

      - name: Formating code
        run: npm run format:check

      - name: Testing projects
        run: npm run test

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build the tagged Docker image
        run: docker build -f ./packages/api-catalog/Dockerfile -t federated-graphql-cicd-api-catalog:dev .

      - name: Push image
        run: |
          IMAGE_ID=${{ secrets.DOCKER_REGISTRY_URL }}/federated-graphql-cicd-api-catalog
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
